#!/bin/bash
# Original script by Mario Finelli <mario at finel dot li>

prgName="foobar2000"
prgRealPath="/usr/share/$prgName"
prgHome="$HOME/.$prgName"
prgBin="$prgName.exe"
prgPrefix="$HOME/.local/share/wineprefixes/$prgName"

# Symlink stuff
mkdir -p "$prgHome" || exit 1
mkdir -p "$HOME/.local/share/wineprefixes" || exit 1
# Delete broken symlinks
find -L "$prgHome" -type l -delete
# Update existing symlinks, add new symlinks
cp -urs "$prgRealPath/"* "$prgHome" 2> /dev/null

# Switches: use -something instead of /something to avoid confusion with Unix paths
# Also convert Unix paths to Windows paths.
declare -a args

for arg; do
    if [[ "${arg:0:1}" = "-" ]]; then
        args+=("${arg/#-//}")
    else
        args+=("$(winepath -w "$arg")")
    fi
done

# wine "$prgHome/$prgBin" "${args[@]}"
WINEPREFIX="$prgPrefix" wine "$prgHome/$prgBin" "${args[@]}"
